# Generated by Django 2.0.13 on 2019-04-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoextrausuario',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
