# Generated by Django 2.2.5 on 2019-10-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('id_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reservacion', models.DateField()),
                ('hora_reservacion', models.TimeField()),
                ('num_personas', models.IntegerField()),
                ('nombre_reservacion', models.CharField(max_length=100)),
                ('telefono_reservacion', models.BigIntegerField()),
                ('correo_reservacion', models.CharField(max_length=100)),
            ],
        ),
    ]
